-- Database Schema Extension for Cascade Updates and Multi-Participant Variables
-- Run this after the main database setup (db.sql)

-- Common Blocks Table
-- Stores the master version of reusable text blocks (House Rules, Confidentiality, etc.)
CREATE TABLE IF NOT EXISTS common_blocks (
  id SERIAL PRIMARY KEY,
  block_id VARCHAR(255) UNIQUE NOT NULL, -- e.g., 'common.house_rules'
  title VARCHAR(500) NOT NULL,
  content TEXT NOT NULL,
  version VARCHAR(50) NOT NULL DEFAULT '1.0.0',
  last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tags TEXT[], -- Array of tags for categorization
  used_in TEXT[], -- Array of template IDs that use this block
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Block Versions Table
-- Maintains version history for common blocks with audit trail
CREATE TABLE IF NOT EXISTS block_versions (
  id SERIAL PRIMARY KEY,
  block_id VARCHAR(255) NOT NULL REFERENCES common_blocks(block_id) ON DELETE CASCADE,
  version VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  change_description TEXT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  changed_by VARCHAR(255), -- User ID or username who made the change
  UNIQUE(block_id, version)
);

-- Forked Blocks Table
-- Tracks documents that have modified a common block
CREATE TABLE IF NOT EXISTS forked_blocks (
  id SERIAL PRIMARY KEY,
  document_instance_id INTEGER NOT NULL,
  block_id VARCHAR(255) NOT NULL REFERENCES common_blocks(block_id) ON DELETE CASCADE,
  original_version VARCHAR(50) NOT NULL,
  modified_content TEXT NOT NULL,
  needs_review BOOLEAN DEFAULT TRUE,
  reviewed_at TIMESTAMP,
  reviewed_by VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(document_instance_id, block_id)
);

-- Participant Groups Table
-- Manages multi-participant document instances (e.g., 3 tenants on a shared lease)
CREATE TABLE IF NOT EXISTS participant_groups (
  id SERIAL PRIMARY KEY,
  document_instance_id INTEGER NOT NULL, -- Foreign key to document_instances table
  template_id VARCHAR(255) NOT NULL,
  participant_count INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(document_instance_id, template_id)
);

-- Participant Variables Table
-- Stores indexed variables for each participant (tenant1.name, tenant2.name, etc.)
CREATE TABLE IF NOT EXISTS participant_variables (
  id SERIAL PRIMARY KEY,
  group_id INTEGER NOT NULL REFERENCES participant_groups(id) ON DELETE CASCADE,
  participant_index INTEGER NOT NULL, -- 1, 2, 3, etc.
  base_variable_name VARCHAR(255) NOT NULL, -- e.g., 'participant.personal.full_name'
  full_variable_name VARCHAR(255) NOT NULL, -- e.g., 'tenant1.personal.full_name'
  value TEXT,
  inherited_from VARCHAR(255), -- Master variable if applicable (e.g., 'entity.trading.name') or master reference (e.g., 'REF-001')
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(group_id, full_variable_name)
);

-- Cascade Tasks Table
-- Tracks tasks generated by cascade updates and fork reviews
CREATE TABLE IF NOT EXISTS cascade_tasks (
  id SERIAL PRIMARY KEY,
  task_id VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(500) NOT NULL,
  type VARCHAR(50) NOT NULL, -- 'cascade_update', 'fork_review', 'external_platform'
  block_id VARCHAR(255) REFERENCES common_blocks(block_id) ON DELETE CASCADE,
  affected_items TEXT[], -- Array of template IDs or document IDs
  completed BOOLEAN DEFAULT FALSE,
  completed_at TIMESTAMP,
  completed_by VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_block_versions_block_id ON block_versions(block_id);
CREATE INDEX IF NOT EXISTS idx_forked_blocks_document_id ON forked_blocks(document_instance_id);
CREATE INDEX IF NOT EXISTS idx_forked_blocks_needs_review ON forked_blocks(needs_review);
CREATE INDEX IF NOT EXISTS idx_participant_groups_document_id ON participant_groups(document_instance_id);
CREATE INDEX IF NOT EXISTS idx_participant_variables_group_id ON participant_variables(group_id);
CREATE INDEX IF NOT EXISTS idx_cascade_tasks_completed ON cascade_tasks(completed);
CREATE INDEX IF NOT EXISTS idx_cascade_tasks_type ON cascade_tasks(type);

-- Triggers for automatic timestamp updates
CREATE OR REPLACE FUNCTION update_modified_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.modified_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_common_blocks_timestamp
BEFORE UPDATE ON common_blocks
FOR EACH ROW
EXECUTE FUNCTION update_modified_timestamp();

CREATE TRIGGER update_participant_groups_timestamp
BEFORE UPDATE ON participant_groups
FOR EACH ROW
EXECUTE FUNCTION update_modified_timestamp();

CREATE TRIGGER update_participant_variables_timestamp
BEFORE UPDATE ON participant_variables
FOR EACH ROW
EXECUTE FUNCTION update_modified_timestamp();

-- Sample data for common blocks
INSERT INTO common_blocks (block_id, title, content, version, tags, used_in) VALUES
(
  'common.house_rules',
  'House Rules',
  '<h3>House Rules</h3><ul><li>Respect and safety</li><li>Cleanliness and maintenance</li><li>Noise and quiet hours</li></ul>',
  '1.0.0',
  ARRAY['residential', 'shared-living', 'rules'],
  ARRAY['TRIAL_LICENSE_AGREEMENT', 'PROBATION_TENANCY', 'SHARED_RESIDENTIAL_LEASE', 'TEAM_MEMBER_AGREEMENT']
),
(
  'common.confidentiality',
  'Confidentiality',
  '<h3>Confidentiality</h3><p>All personal information will be kept confidential...</p>',
  '1.0.0',
  ARRAY['legal', 'privacy', 'security'],
  ARRAY['TRIAL_LICENSE_AGREEMENT', 'TEAM_MEMBER_AGREEMENT', 'FACILITATOR_AGREEMENT']
),
(
  'common.emergency_procedures',
  'Emergency Procedures',
  '<h3>Emergency Procedures</h3><ul><li>Fire safety</li><li>Medical emergencies</li><li>Security threats</li></ul>',
  '1.0.0',
  ARRAY['safety', 'emergency', 'procedures'],
  ARRAY['TRIAL_LICENSE_AGREEMENT', 'PROBATION_TENANCY', 'SHARED_RESIDENTIAL_LEASE', 'GUEST_EXPERIENCE_AGREEMENT']
)
ON CONFLICT (block_id) DO NOTHING;

-- Initial version history for common blocks
INSERT INTO block_versions (block_id, version, content, change_description) VALUES
('common.house_rules', '1.0.0', '<h3>House Rules</h3><ul><li>Respect and safety</li><li>Cleanliness and maintenance</li><li>Noise and quiet hours</li></ul>', 'Initial version'),
('common.confidentiality', '1.0.0', '<h3>Confidentiality</h3><p>All personal information will be kept confidential...</p>', 'Initial version'),
('common.emergency_procedures', '1.0.0', '<h3>Emergency Procedures</h3><ul><li>Fire safety</li><li>Medical emergencies</li><li>Security threats</li></ul>', 'Initial version')
ON CONFLICT (block_id, version) DO NOTHING;
