/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:3d72b6f1-a857-4148-8f01-ae3ab2c24c9b",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_IR2j3yHPR",
    "aws_user_pools_web_client_id": "un0t3utbt8p4a77jfang6fe3p",
    "oauth": {
        "domain": "ap-southeast-2do0zvzlo7.auth.ap-southeast-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "profile"
        ],
        "redirectSignIn": "https://lab.crusaders.clockwork.vip/oauth2/idpresponse",
        "redirectSignOut": "https://lab.crusaders.clockwork.vip/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE",
        "AMAZON"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
